[package]
name = "molyidev/ignis"
version = "0.1.0"
description = "Framework library."
authors = ["Molyi"]
registry = "https://github.com/UpliftGames/wally-index"
repository = "https://github.com/MolyiDev/Ignis"
license = "MIT"
realm = "shared"
exclude = ["**"]
include = ["wally.toml", "default.project.json", "README.md", "LICENSE", "src", "src/**"]

[dependencies]
